package selenium.ide;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

/** @author : Matteo Calzetta matricola 0273429
 */

public class TestDivisionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/java/selenium/Driver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testDivision() {
    // Test name: TestDivision
    // Step # | name | target | value
    // 1 | open | https://www.calculator.net/ | 
    driver.get("https://www.calculator.net/");
    // 2 | setWindowSize | 1397x748 | 
    driver.manage().window().setSize(new Dimension(1397, 748));
    // 3 | click | css=div:nth-child(1) > .scinm:nth-child(3) | 
    driver.findElement(By.cssSelector("div:nth-child(1) > .scinm:nth-child(3)")).click();
    // 4 | click | css=div:nth-child(4) > .sciop:nth-child(4) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .sciop:nth-child(4)")).click();
    // 5 | click | css=div:nth-child(2) > .scinm:nth-child(2) | 
    driver.findElement(By.cssSelector("div:nth-child(2) > .scinm:nth-child(2)")).click();
    // 6 | click | css=.scieq:nth-child(4) | 
    driver.findElement(By.cssSelector(".scieq:nth-child(4)")).click();
    // 7 | click | id=sciout | 
    driver.findElement(By.id("sciout")).click();

    assertEquals("1.8", driver.findElement(By.id("sciOutPut")).getText().substring(1));
  }
}